import { execSync } from "node:child_process";
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { NativitePluginMode } from "../../index.ts";
import type { NativiteConfig } from "../../index.ts";

import { DEFAULT_ANDROID_MIN_SDK, DEFAULT_ANDROID_TARGET_SDK } from "../../index.ts";
import { resolveConfigForPlatform } from "../../platforms/registry.ts";
import { resolveNativitePlugins } from "../../plugins/resolve.ts";
import { androidManifestTemplate } from "./android-manifest.ts";
import { appIconTemplate, appIconXmlTemplate } from "./app-icon.ts";
import { buildGradleAppTemplate } from "./build-gradle-app.ts";
import { buildGradleRootTemplate } from "./build-gradle-root.ts";
import { syncAndroidDevMetadata } from "./dev-metadata.ts";
import { gradlePropertiesTemplate } from "./gradle-properties.ts";
import { gradleWrapperPropertiesTemplate } from "./gradle-wrapper-properties.ts";
import { hashConfigForGeneration } from "./hash.ts";
import { mainActivityTemplate } from "./main-activity.ts";
import { nativitePluginRegistrantTemplate } from "./nativite-plugin-registrant.ts";
import { stringsXmlTemplate, colorsXmlTemplate, themesXmlTemplate } from "./resources.ts";
import { settingsGradleTemplate } from "./settings-gradle.ts";
import { splashScreenTemplate } from "./splash-screen.ts";
import { versionCatalogTemplate } from "./version-catalog.ts";

const runtimeDir = join(dirname(fileURLToPath(import.meta.url)), "runtime");

function safePluginDirName(pluginName: string): string {
  return pluginName.replace(/[^A-Za-z0-9_.-]/g, "_");
}

function pluginInputDestination(
  file: { readonly pluginName: string; readonly absolutePath: string },
  outputRoot: string,
  preserveFileParentDir: boolean,
): string {
  const sourceStat = statSync(file.absolutePath);
  const destinationRoot = join(outputRoot, safePluginDirName(file.pluginName));

  if (!sourceStat.isDirectory() && preserveFileParentDir) {
    return join(destinationRoot, basename(dirname(file.absolutePath)), basename(file.absolutePath));
  }

  return join(destinationRoot, basename(file.absolutePath));
}

function pluginInputDirs(
  files: readonly { readonly pluginName: string; readonly absolutePath: string }[],
  outputRoot: string,
  preserveFileParentDir = false,
): string[] {
  const dirs = new Set<string>();

  for (const file of files) {
    const destination = pluginInputDestination(file, outputRoot, preserveFileParentDir);
    dirs.add(statSync(file.absolutePath).isDirectory() ? destination : dirname(destination));
  }

  return [...dirs].sort((a, b) => a.localeCompare(b));
}

function copyPluginInputs(
  files: readonly { readonly pluginName: string; readonly absolutePath: string }[],
  outputRoot: string,
  preserveFileParentDir = false,
): string[] {
  for (const file of files) {
    const source = file.absolutePath;
    const destination = pluginInputDestination(file, outputRoot, preserveFileParentDir);
    mkdirSync(dirname(destination), { recursive: true });
    cpSync(source, destination, { recursive: true });
  }

  return pluginInputDirs(files, outputRoot, preserveFileParentDir);
}

function readRuntimeFile(pkg: string, filename: string): string {
  const src = readFileSync(join(runtimeDir, filename), "utf-8");
  return `package ${pkg}\n\n${src}`;
}

function nativiteConfigTemplate(pkg: string, config: NativiteConfig): string {
  const defaultChromeStateJSON = config.defaultChrome
    ? JSON.stringify(JSON.stringify(config.defaultChrome))
    : "null";

  return `package ${pkg}

// Generated by Nativite — do not edit.
object NativiteConfig {
    val defaultChromeStateJSON: String? = ${defaultChromeStateJSON}
}
`;
}

function generationHashInputs(
  config: NativiteConfig,
  resolvedPlugins: Awaited<ReturnType<typeof resolveNativitePlugins>>,
  pluginSourceDir: string,
  pluginResourceDir: string,
) {
  const androidConfig = resolveConfigForPlatform(config, "android");
  const androidPlatform = (config.platforms ?? []).find((p) => p.platform === "android");
  const minSdk =
    (androidPlatform as { minSdk?: number } | undefined)?.minSdk ?? DEFAULT_ANDROID_MIN_SDK;
  const targetSdk =
    (androidPlatform as { targetSdk?: number } | undefined)?.targetSdk ??
    DEFAULT_ANDROID_TARGET_SDK;
  const pkg = androidConfig.app.bundleId;
  const pluginDependencies = resolvedPlugins.platforms.android.dependencies.filter(
    (dependency) => dependency.kind === "gradle",
  );

  return [
    { name: "settings.gradle.kts", content: settingsGradleTemplate(androidConfig.app.name) },
    { name: "build.gradle.kts", content: buildGradleRootTemplate() },
    { name: "gradle.properties", content: gradlePropertiesTemplate() },
    {
      name: "gradle/wrapper/gradle-wrapper.properties",
      content: gradleWrapperPropertiesTemplate(),
    },
    { name: "gradle/libs.versions.toml", content: versionCatalogTemplate() },
    {
      name: "app/build.gradle.kts",
      content: buildGradleAppTemplate(androidConfig, minSdk, targetSdk, {
        sourceDirs: pluginInputDirs(resolvedPlugins.platforms.android.sources, pluginSourceDir),
        resourceDirs: pluginInputDirs(
          resolvedPlugins.platforms.android.resources,
          pluginResourceDir,
          true,
        ),
        dependencies: pluginDependencies,
      }),
    },
    { name: "AndroidManifest.xml", content: androidManifestTemplate(androidConfig) },
    { name: "MainActivity.kt", content: mainActivityTemplate(androidConfig) },
    { name: "NativiteConfig.kt", content: nativiteConfigTemplate(pkg, config) },
    { name: "NativiteBridge.kt", content: readRuntimeFile(pkg, "NativiteBridge.kt") },
    { name: "NativiteChrome.kt", content: readRuntimeFile(pkg, "NativiteChrome.kt") },
    { name: "NativiteWebView.kt", content: readRuntimeFile(pkg, "NativiteWebView.kt") },
    { name: "NativiteVars.kt", content: readRuntimeFile(pkg, "NativiteVars.kt") },
    { name: "NativiteTheme.kt", content: readRuntimeFile(pkg, "NativiteTheme.kt") },
    {
      name: "NativitePluginRegistrant.kt",
      content: `package ${pkg}\n\n${nativitePluginRegistrantTemplate(resolvedPlugins)}`,
    },
    { name: "strings.xml", content: stringsXmlTemplate(androidConfig) },
    { name: "colors.xml", content: colorsXmlTemplate() },
    { name: "themes.xml", content: themesXmlTemplate(androidConfig) },
    ...(androidConfig.splash
      ? [{ name: "splash.xml", content: splashScreenTemplate(androidConfig) }]
      : []),
    { name: "ic_launcher.xml", content: appIconXmlTemplate() },
    { name: "ic_launcher_foreground.png", content: appIconTemplate() },
  ];
}

export interface GenerateResult {
  readonly skipped: boolean;
  readonly projectPath: string;
  readonly hash: string;
}

export async function generateProject(
  config: NativiteConfig,
  cwd: string,
  force = false,
  mode: NativitePluginMode = "generate",
): Promise<GenerateResult> {
  const nativiteDir = join(cwd, ".nativite");
  const hashFile = join(nativiteDir, ".hash-android");
  const projectRoot = join(nativiteDir, "android");
  const androidConfig = resolveConfigForPlatform(config, "android");
  const resolvedPlugins = await resolveNativitePlugins(config, cwd, mode);
  const appDir = join(projectRoot, "app");
  const srcMainDir = join(appDir, "src", "main");
  const pluginSourceDir = join(srcMainDir, "generated", "nativite", "plugins", "java");
  const pluginResourceDir = join(srcMainDir, "generated", "nativite", "plugins", "res");
  const hash = hashConfigForGeneration(
    config,
    resolvedPlugins,
    generationHashInputs(config, resolvedPlugins, pluginSourceDir, pluginResourceDir),
  );

  // Ensure production/generate mode never packages stale dev server settings.
  syncAndroidDevMetadata(cwd, mode);

  // Dirty check — skip if nothing has changed
  if (!force && existsSync(hashFile)) {
    const existingHash = readFileSync(hashFile, "utf-8").trim();
    if (existingHash === hash) {
      return {
        skipped: true,
        projectPath: projectRoot,
        hash,
      };
    }
  }

  const androidPlatform = (config.platforms ?? []).find((p) => p.platform === "android");
  const minSdk =
    (androidPlatform as { minSdk?: number } | undefined)?.minSdk ?? DEFAULT_ANDROID_MIN_SDK;
  const targetSdk =
    (androidPlatform as { targetSdk?: number } | undefined)?.targetSdk ??
    DEFAULT_ANDROID_TARGET_SDK;

  const packagePath = androidConfig.app.bundleId.split(".");
  const javaDir = join(srcMainDir, "java", ...packagePath);
  const resDir = join(srcMainDir, "res");
  const valuesDir = join(resDir, "values");
  const mipmapXxxhdpiDir = join(resDir, "mipmap-xxxhdpi");
  const mipmapAnydpiDir = join(resDir, "mipmap-anydpi-v26");
  const assetsDir = join(srcMainDir, "assets");
  const gradleWrapperDir = join(projectRoot, "gradle", "wrapper");

  for (const dir of [
    nativiteDir,
    projectRoot,
    appDir,
    srcMainDir,
    javaDir,
    resDir,
    valuesDir,
    mipmapXxxhdpiDir,
    mipmapAnydpiDir,
    assetsDir,
    pluginSourceDir,
    pluginResourceDir,
    gradleWrapperDir,
  ]) {
    mkdirSync(dir, { recursive: true });
  }

  // Generate Gradle wrapper (gradlew, gradlew.bat, gradle-wrapper.jar) before
  // writing build files — Gradle evaluates build scripts during configuration,
  // so build.gradle.kts must not exist yet.
  writeFileSync(
    join(projectRoot, "settings.gradle.kts"),
    settingsGradleTemplate(androidConfig.app.name),
  );
  execSync("gradle wrapper --gradle-version 8.11.1 --no-daemon", {
    cwd: projectRoot,
    stdio: "pipe",
    timeout: 60_000,
  });

  // Root build files
  writeFileSync(join(projectRoot, "build.gradle.kts"), buildGradleRootTemplate());
  writeFileSync(join(projectRoot, "gradle.properties"), gradlePropertiesTemplate());
  writeFileSync(
    join(gradleWrapperDir, "gradle-wrapper.properties"),
    gradleWrapperPropertiesTemplate(),
  );

  // Version catalog
  const gradleDir = join(projectRoot, "gradle");
  mkdirSync(gradleDir, { recursive: true });
  writeFileSync(join(gradleDir, "libs.versions.toml"), versionCatalogTemplate());

  const pluginSourceDirs = copyPluginInputs(
    resolvedPlugins.platforms.android.sources,
    pluginSourceDir,
  );
  const pluginResourceDirs = copyPluginInputs(
    resolvedPlugins.platforms.android.resources,
    pluginResourceDir,
    true,
  );
  const pluginDependencies = resolvedPlugins.platforms.android.dependencies.filter(
    (dependency) => dependency.kind === "gradle",
  );

  // App module build file
  writeFileSync(
    join(appDir, "build.gradle.kts"),
    buildGradleAppTemplate(androidConfig, minSdk, targetSdk, {
      sourceDirs: pluginSourceDirs,
      resourceDirs: pluginResourceDirs,
      dependencies: pluginDependencies,
    }),
  );

  // Android manifest
  writeFileSync(join(srcMainDir, "AndroidManifest.xml"), androidManifestTemplate(androidConfig));

  // Kotlin source files
  const pkg = androidConfig.app.bundleId;
  writeFileSync(join(javaDir, "MainActivity.kt"), mainActivityTemplate(androidConfig));
  writeFileSync(join(javaDir, "NativiteConfig.kt"), nativiteConfigTemplate(pkg, config));
  writeFileSync(join(javaDir, "NativiteBridge.kt"), readRuntimeFile(pkg, "NativiteBridge.kt"));
  writeFileSync(join(javaDir, "NativiteChrome.kt"), readRuntimeFile(pkg, "NativiteChrome.kt"));
  writeFileSync(join(javaDir, "NativiteWebView.kt"), readRuntimeFile(pkg, "NativiteWebView.kt"));
  writeFileSync(join(javaDir, "NativiteVars.kt"), readRuntimeFile(pkg, "NativiteVars.kt"));
  writeFileSync(join(javaDir, "NativiteTheme.kt"), readRuntimeFile(pkg, "NativiteTheme.kt"));
  writeFileSync(
    join(javaDir, "NativitePluginRegistrant.kt"),
    `package ${pkg}\n\n${nativitePluginRegistrantTemplate(resolvedPlugins)}`,
  );

  // Resources
  writeFileSync(join(valuesDir, "strings.xml"), stringsXmlTemplate(androidConfig));
  writeFileSync(join(valuesDir, "colors.xml"), colorsXmlTemplate());
  writeFileSync(join(valuesDir, "themes.xml"), themesXmlTemplate(androidConfig));

  // Splash screen
  if (androidConfig.splash) {
    writeFileSync(join(valuesDir, "splash.xml"), splashScreenTemplate(androidConfig));
  }

  // App icon
  if (androidConfig.icon) {
    const sourceIconPath = resolve(cwd, androidConfig.icon);
    const iconFilename = basename(sourceIconPath);
    copyFileSync(sourceIconPath, join(mipmapXxxhdpiDir, iconFilename));
    writeFileSync(join(mipmapAnydpiDir, "ic_launcher.xml"), appIconXmlTemplate());
  } else {
    writeFileSync(join(mipmapAnydpiDir, "ic_launcher.xml"), appIconXmlTemplate());
  }
  writeFileSync(join(mipmapXxxhdpiDir, "ic_launcher_foreground.png"), appIconTemplate());

  writeFileSync(hashFile, hash);

  return {
    skipped: false,
    projectPath: projectRoot,
    hash,
  };
}
