import type { ResolvedNativitePlugins } from "../../plugins/resolve.ts";

export function nativitePluginRegistrantTemplate(resolvedPlugins: ResolvedNativitePlugins): string {
  const registrars = resolvedPlugins.platforms.android.registrars;
  const calls =
    registrars.length > 0
      ? registrars.map((registrar) => `    ${registrar}(bridge)`).join("\n")
      : "    // No Android plugins registered.";

  return `// Auto-generated by Nativite. This file centralises Android plugin bridge registration.
fun registerNativitePlugins(bridge: NativiteBridge) {
${calls}
}
`;
}
