import type { ResolvedNativitePlugins } from "../../plugins/resolve.ts";

function registrarCallName(registrar: string): string {
  return registrar.split(".").at(-1)!;
}

export function nativitePluginRegistrantTemplate(resolvedPlugins: ResolvedNativitePlugins): string {
  const registrars = resolvedPlugins.platforms.android.registrars;
  const imports = registrars
    .filter((registrar) => registrar.includes("."))
    .map((registrar) => `import ${registrar}`)
    .sort((a, b) => a.localeCompare(b));
  const importBlock = imports.length > 0 ? `${imports.join("\n")}\n\n` : "";
  const calls =
    registrars.length > 0
      ? registrars.map((registrar) => `    ${registrarCallName(registrar)}(bridge)`).join("\n")
      : "    // No Android plugins registered.";

  return `${importBlock}// Auto-generated by Nativite. This file centralises Android plugin bridge registration.
fun registerNativitePlugins(bridge: NativiteBridge) {
${calls}
}
`;
}
