import type { ResolvedNativitePlugins } from "../../plugins/resolve.ts";

function swiftString(value: string): string {
  return JSON.stringify(value);
}

function unsupportedMacOSRegistrations(resolvedPlugins: ResolvedNativitePlugins): string[] {
  const registrations = new Map<string, Set<string>>();

  for (const plugin of resolvedPlugins.plugins) {
    if (!plugin.name.startsWith("nativite-")) continue;
    const hasMacOSImplementation =
      plugin.platforms.macos.sources.length > 0 || plugin.platforms.macos.registrars.length > 0;
    if (hasMacOSImplementation) continue;

    for (const namespace of plugin.bridgeNamespaces ?? []) {
      if (!namespace.methods || namespace.methods.length === 0) continue;
      const methods = registrations.get(namespace.name) ?? new Set<string>();
      for (const method of namespace.methods) {
        methods.add(method);
      }
      registrations.set(namespace.name, methods);
    }
  }

  return [...registrations.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([namespace, methods]) => {
      const methodList = [...methods]
        .sort((a, b) => a.localeCompare(b))
        .map(swiftString)
        .join(", ");
      return `  registerUnsupportedNativitePluginNamespace(bridge, namespace: ${swiftString(namespace)}, methods: [${methodList}])`;
    });
}

export function nativitePluginRegistrantTemplate(resolvedPlugins: ResolvedNativitePlugins): string {
  const iosRegistrars = resolvedPlugins.platforms.ios.registrars;
  const macosRegistrars = resolvedPlugins.platforms.macos.registrars;
  const macosUnsupportedRegistrations = unsupportedMacOSRegistrations(resolvedPlugins);

  const iosCalls =
    iosRegistrars.length > 0
      ? iosRegistrars.map((symbol) => `  ${symbol}(bridge)`).join("\n")
      : "  // No iOS plugins registered.";
  const macosRegistrationCalls = [
    ...macosRegistrars.map((symbol) => `  ${symbol}(bridge)`),
    ...macosUnsupportedRegistrations,
  ];
  const macosCalls =
    macosRegistrationCalls.length > 0
      ? macosRegistrationCalls.join("\n")
      : "  // No macOS plugins registered.";

  return `import Foundation

private let nativiteUnsupportedPluginErrorDomain = "NativiteUnsupportedPlugin"

private func nativiteUnsupportedPluginError(namespace: String, method: String) -> NSError {
  let payload = [
    "code": "unsupported",
    "message": "\\(namespace).\\(method) is not supported on macOS by this Nativite plugin.",
    "platform": "macos",
    "operation": method,
  ]
  let jsonMessage = (try? JSONSerialization.data(withJSONObject: payload))
    .flatMap { String(data: $0, encoding: .utf8) }
    ?? "{\\"code\\":\\"unsupported\\",\\"message\\":\\"Plugin method is not supported on macOS\\",\\"platform\\":\\"macos\\",\\"operation\\":\\"\\(method)\\"}"

  return NSError(
    domain: nativiteUnsupportedPluginErrorDomain,
    code: 1,
    userInfo: [NSLocalizedDescriptionKey: jsonMessage]
  )
}

private func registerUnsupportedNativitePluginNamespace(
  _ bridge: NativiteBridge,
  namespace: String,
  methods: [String]
) {
  for method in methods {
    bridge.register(namespace: namespace, method: method) { _, completion in
      completion(.failure(nativiteUnsupportedPluginError(namespace: namespace, method: method)))
    }
  }
}

// Auto-generated by Nativite. This file centralises plugin bridge registration.
func registerNativitePlugins(on bridge: NativiteBridge) {
#if os(iOS)
${iosCalls}
#elseif os(macOS)
${macosCalls}
#endif
}
`;
}
