import type { ResolvedNativitePlugins } from "../../plugins/resolve.ts";

export function nativitePluginRegistrantTemplate(resolvedPlugins: ResolvedNativitePlugins): string {
  const iosRegistrars = resolvedPlugins.platforms.ios.registrars;
  const macosRegistrars = resolvedPlugins.platforms.macos.registrars;

  const iosCalls =
    iosRegistrars.length > 0
      ? iosRegistrars.map((symbol) => `  ${symbol}(bridge)`).join("\n")
      : "  // No iOS plugins registered.";
  const macosCalls =
    macosRegistrars.length > 0
      ? macosRegistrars.map((symbol) => `  ${symbol}(bridge)`).join("\n")
      : "  // No macOS plugins registered.";

  return `import Foundation

// Auto-generated by Nativite. This file centralises plugin bridge registration.
func registerNativitePlugins(on bridge: NativiteBridge) {
#if os(iOS)
${iosCalls}
#elseif os(macOS)
${macosCalls}
#endif
}
`;
}
